apiVersion: v1
kind: ConfigMap
metadata:
  name: dbconfigmap
data:
  DB_NAME: "tm-udacity-coworking-db"
  DB_USER: "tm-udacity-coworking-db-user"
  DB_HOST: "postgresql-service"
  DB_PORT: "5421"
---
apiVersion: v1
kind: Secret
metadata:
  name: dbpassword
type: Opaque
data:
  dbpassword: dG0tdWRhY2l0eS1jb3dvcmtpbmctZGItdVI=